---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Install python-apt
    raw: |
      apt-get update && apt-get -y install sudo python3 python3-apt
    become_method: su
    changed_when: false
  - name: install openssh client
    package:
      name: openssh-client
      state: present
