---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-users-${MOLECULE_SCENARIO_NAME}
    image: debian:stable
    pre_build_image: true
    command: sleep 1d
provisioner:
  name: ansible
  inventory:
    group_vars:
      ansible_python_interpreter: /usr/bin/python3
  config_options:
    ssh_connection:
      pipelining: true
verifier:
  name: testinfra
